namespace MAUISqlite;

// This is the entry point of the application. The App class is a partial class
// that represents the application and is responsible for initializing it.

public partial class App : Application
{
    // The constructor of the App class. It is called when the application starts.

	public App()
	{
	  // InitializeComponent is a method generated by the Xamarin.Forms framework
        // that initializes the application's main components and resources.
        InitializeComponent();

        // Create and set the MainPage of the application to a new instance of the AppShell.
        // AppShell is typically used as the main navigation container for the application.
        MainPage = new AppShell();
	}
}
